### ISSUE TITLE
Prices with silver values under 10 return incorrectly - no padding 0

### ISSUE THREAD

**Issue by audiosmith** [scrable/TradeSkillMaster_PriceChecker#8]
![image](https://user-images.githubusercontent.com/9102111/78000446-c40ea380-7390-11ea-9b67-285ea8c54156.png)

**Comment by audiosmith** [comment]
The Black Mageweave gloves should be 1.09 min 1.02 market
Whisper sent 1.9 and 1.2 suggesting the leading 0 is being omitted

**Comment by scrable** [comment]
Should be fixed

https://github.com/scrable/TradeSkillMaster_PriceChecker/releases/tag/v1.13

**Comment by alphabitnz** [comment]
still happening 
![image](https://user-images.githubusercontent.com/9102111/78510573-3dbbec80-77ea-11ea-9f1a-63f74f2c4863.png)

**Comment by scrable** [comment]
Interesting. I logged in as a trial account and tried it out, it appears to be working on my side, so I'm not sure what could be wrong. I won't have time to look into it until later tomorrow night.

![unsure](https://user-images.githubusercontent.com/5439514/78525672-ae342080-778c-11ea-8e42-17c2f9a44f72.PNG)
![1](https://user-images.githubusercontent.com/5439514/78525671-ad9b8a00-778c-11ea-8eba-9fde7f14b6a3.PNG)
![4](https://user-images.githubusercontent.com/5439514/78525673-ae342080-778c-11ea-92de-a80dfd45e0ca.PNG)
![3](https://user-images.githubusercontent.com/5439514/78525674-aeccb700-778c-11ea-9095-cf054ed67de8.PNG)
![2](https://user-images.githubusercontent.com/5439514/78525675-aeccb700-778c-11ea-84da-4dfe901afe8d.PNG)

**Comment by alphabitnz** [comment]
## Interface: 80100
## Title: |cff00ff00TSM_PriceChecker|r
## Notes: Replies to price checks based off of TSM prices
## Author: seraph1m
## Version: v1.0.7
## RequiredDeps: TradeSkillMaster
## SavedVariables: TSM_PriceCheckerDB

Libs\LibStub\LibStub.lua

Locale\enUS.lua
Locale\deDE.lua
Locale\esES.lua
Locale\esMX.lua
Locale\frFR.lua
Locale\koKR.lua
Locale\ruRU.lua
Locale\zhCN.lua
Locale\zhTW.lua
Locale\ptBR.lua

TSM_PriceChecker.lua
Modules\Util.lua
Modules\Options.lua
Modules\EventDetection.lua

**Comment by alphabitnz** [comment]
Savedvariables:


TSM_PriceCheckerDB = {
	["profileKeys"] = {
		["(censored)"] = "Default",
		-- etc...
	},
	["global"] = {
		["TriggerLength"] = 1,
	},
}

**Comment by scrable** [comment]
Thanks, I'll take a look tomorrow evening.

If it is at all possible, can you post the contents of Util.lua file within the Modules folder?

**Comment by alphabitnz** [comment]
Sure, I always delete the whole addon folder when upgrading. Here it is:
[Util.lua.txt](https://github.com/scrable/TradeSkillMaster_PriceChecker/files/4436169/Util.lua.txt)

**Comment by scrable** [comment]
Ah yes, I think that's the issue. It looks like that file you have locally doesn't have the changes I made to fix the issue for some reason. Can you try redownloading from [here](https://github.com/scrable/TradeSkillMaster_PriceChecker/releases/tag/v1.13) and let me know?

**Comment by alphabitnz** [comment]
sorry for the delay, this is fixed
